In [1]:
import numpy as np

In [2]:
p = [1,2,3,4,5]
p

[1, 2, 3, 4, 5]

In [3]:
n = np.array([1,2,3,4,5])
n

array([1, 2, 3, 4, 5])

In [4]:
p[0:2]

[1, 2]

In [5]:
n[0:2]

array([1, 2])

In [6]:
for i in n:
    print(i)

1
2
3
4
5


In [7]:
p = [[1,2,3],[2,3,4]]
p[0][1]

2

In [8]:
n = np.array([[1,2,3],[2,3,4]])
n

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
n[0,1]

2

In [10]:
np.arange(2000)

array([   0,    1,    2, ..., 1997, 1998, 1999])

In [11]:
np.arange(0.0, 9.9, .3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 6. , 6.3, 6.6, 6.9, 7.2, 7.5,
       7.8, 8.1, 8.4, 8.7, 9. , 9.3, 9.6])

In [12]:
np.zeros(20000)

array([0., 0., 0., ..., 0., 0., 0.])

In [13]:
np.zeros(200000, dtype=np.uint16)

array([0, 0, 0, ..., 0, 0, 0], dtype=uint16)

In [14]:
n = np.array([2,4,6])
n + 25

array([27, 29, 31])

In [15]:
import math
n =[2,3,4]
[math.sin(i) for i in n]

[0.9092974268256817, 0.1411200080598672, -0.7568024953079282]

In [16]:
a = np.array([1,2,3])
b = np.array([1,2])
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [17]:
a = np.array([[1,2,3], [1,2,3]])
b = np.array([1,2,3])
a + b

array([[2, 4, 6],
       [2, 4, 6]])

In [18]:
a = np.arange(10,30)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [19]:
a[0:3]

array([10, 11, 12])

In [20]:
a[0:25:5]

array([10, 15, 20, 25])

In [21]:
a[ [1,3,5] ]

array([11, 13, 15])

In [22]:
a > 13

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [23]:
a[a > 13]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
a % 3

array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])

In [25]:
a % 3 == 0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [26]:
a[a % 3 == 0]

array([12, 15, 18, 21, 24, 27])